# Generated by configure script
# Do not edit manually - run ./configure to regenerate

PREFIX = /home/pjobson
BINDIR = /home/pjobson/bin

CXX = g++
CXXFLAGS = -std=c++17 -O3 -Wall -Werror
LDFLAGS = 

PNGPP_INCLUDES = 
LIBPNG_CFLAGS = -I/usr/include/libpng16 
LIBPNG_LIBS = -lpng16 
SNDFILE_CFLAGS = -I/usr/include/opus -I/usr/include/x86_64-linux-gnu 
SNDFILE_LIBS = -lsndfile 
BOOST_LIBS = -lboost_program_options

ENABLE_DEBUG = no
ENABLE_PROFILING = no
